### ISSUE TITLE
consider merging overloads that take ownership of a value

### ISSUE THREAD

**Issue by kitegi** [lamarrr/STX#28]
rather than having two overloads, one that takes by `const&` and another that takes by `&&`, we could merge them into a single one that takes the object by value, then moves it into its slot.

with two reference constructors, passing an lvalue calls the copy constructor, and passing an rvalue calls the move constructor
with one value constructor, passing an lvalue calls the copy constructor, then the move constructor, and passing an rvalue calls the move constructor twice.

so the cost is having to move the object one more time. but moves are cheap and compilers can elide them in most cases where it matters ( [example](https://godbolt.org/z/YTca1q) , we get roughly equivalent generated assembly with a vector, for instance)

on the other hand, this can help avoid code duplication, and lessen the load on the compiler that comes from having to resolve the correct overload in each instantiation

**Comment by lamarrr** [comment]
Hi there.
With an `**r-value ref**` we move only once. With an rvalue overload as in yours, there could potentially be multiple moves (1-move-construction, then one move). STX's result API is r-value move-first. Especially whilst trying to prioritize Result's use as a return channel. Result for example is a pure forwarding type (making no copies whatsoever unless the user explicitly so desires (and making copies as obvious as possible)).
Your optimization in the example for instance only applies to release builds, primarily due to optimization of memory copies. It won't apply to resource handles that could potentially mutate global state.

**Comment by kitegi** [comment]
could you clarify this part, please?
> Especially whilst trying to prioritize Result's use as a return channel

note that if we're initializing from returned temporaries, then the two methods are equivalent. [we always have to do one move.](https://godbolt.org/z/6oervx)
this is true even in debug builds because of mandatory copy/move elision in c++17

**Comment by lamarrr** [comment]
Copy elision doesn't work in this case since we are not returning the moved value directly.

I.e.

```cpp
stx::Result<vector<int>, Error> fn() {
vector j;
return stx::Ok(j);
}
```

Will not elide the copy of j. 
Now consider that j is a shared_ptr or a heavy type, that would result to an implicit copy which is very expensive in some high-performance cases which STX has high-priority for.
The whole point of move construction is for it to be as cheap as possible and cheaper than a copy. So compilers are very good at optimizing move operations away.
If your type also happens to perform volatile operations on copy, that would have unintended consequences.
